# Site settings
name: 总结珍理(甜心柚的博客)
email: summaryofsuccess@yeah.net
author: 甜心柚
url: https://tianxinyou.github.io/
resume_site: https://tianxinyou.github.io/
github: https://github.com/tianxinyou
baseurl: ''
description: Actually, less is more!
meta_description: 甜心柚;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 学而不思则罔,思而不学则殆
banner: It's our wits that make us men.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 甜心柚
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : tianxinyou
    disqus :
        short_name : tianxinyou
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light